version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=iss
      - POSTGRES_USER=iss_user
      - POSTGRES_PASSWORD=this0is0a0super0secret0password69
  web:
    build:
      context: .
    environment:
      - ISS_SETTINGS_FILE=/opt/ISS/config/settings
      - DJANGO_DEBUG=TRUE
    command: sh /opt/ISS/config/mig-and-run.sh
    volumes:
      - ./docker-config:/opt/ISS/config
      - ./docker-config/banners:/opt/ISS/src/ISS/static/banners
    ports:
      - "8000:8000"
    depends_on:
      - db
