# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 05:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0032_auto_20170522_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='enable_editor_buttons',
            field=models.BooleanField(default=False),
        ),
    ]
