# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 23:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0036_ipban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='normalized_username',
            field=models.CharField(max_length=2048),
        ),
    ]
