# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 00:22


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0037_auto_20170702_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='recovery_code',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='recovery_expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
