# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 18:10


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0039_registrationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessControlList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('allow_by_default', models.BooleanField(default=False)),
                ('black_groups', models.ManyToManyField(related_name='blacklisted_acls', to='ISS.AccessControlGroup')),
                ('black_posters', models.ManyToManyField(related_name='blacklisted_acls', to=settings.AUTH_USER_MODEL)),
                ('white_groups', models.ManyToManyField(related_name='whitelisted_acls', to='ISS.AccessControlGroup')),
                ('white_posters', models.ManyToManyField(related_name='whitelisted_acls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
