# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-09 04:37


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0047_poster_pgp_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_update',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
