# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-09 22:12


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0048_auto_20190109_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='email_verification_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='poster',
            name='pgp_key',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
