# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-30 20:00


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0051_auto_20190210_0919'),
        ('ISS', '0052_thread_stickied'),
    ]

    operations = [
    ]
