# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-14 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0054_auto_20190906_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipban',
            name='expires',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='email_verification_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='theme',
            field=models.CharField(choices=[(b'bibliotek', b'Bibliotek'), (b'&T', b'&T'), (b'amoled', b'AMOLED')], default=b'&T', max_length=256),
        ),
    ]
