# Generated by Django 2.2.9 on 2020-01-26 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0057_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollvote',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ISS.PollOption'),
        ),
    ]
