# Generated by Django 2.2.9 on 2020-02-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0057_auto_20200119_2340'),
        ('ISS', '0058_auto_20200126_0327'),
    ]

    operations = [
    ]
