# Generated by Django 4.2.16 on 2025-07-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0060_banner_alter_poster_theme_alter_poster_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
