# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 02:46


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ISS', '0032_auto_20170522_0438'),
        ('taboo', '0002_auto_20170528_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabooViolationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('phrase', models.CharField(max_length=1024)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taboo_failures', to=settings.AUTH_USER_MODEL)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taboo_successes', to=settings.AUTH_USER_MODEL)),
                ('violating_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ISS.Post')),
            ],
        ),
    ]
