# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0028_auto_20170311_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_from',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
