# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0031_auto_20170503_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='tripphrase',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='threadflag',
            name='last_read_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ISS.Post'),
        ),
    ]
