# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 00:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0033_poster_enable_editor_buttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_package', models.CharField(choices=[(b'ADMIN_REQUIRED', b'ADMIN_REQUIRED'), (b'PERMISSIVE', b'PERMISSIVE')], default=b'PERMISSIVE', max_length=256)),
                ('logic_config', models.TextField(blank=True)),
            ],
        ),
    ]
