# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 00:32


import ISS.models.core_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0034_authpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='create_post_pack',
            field=models.ForeignKey(default=ISS.models.core_models.default_auth_pack, on_delete=django.db.models.deletion.CASCADE, related_name='post_creation_pack', to='ISS.AuthPackage'),
        ),
        migrations.AddField(
            model_name='forum',
            name='create_thread_pack',
            field=models.ForeignKey(default=ISS.models.core_models.default_auth_pack, on_delete=django.db.models.deletion.CASCADE, related_name='thread_creation_pack', to='ISS.AuthPackage'),
        ),
    ]
