# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 21:09
from __future__ import unicode_literals

import ISS.models.registration_code
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0038_auto_20170717_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=ISS.models.registration_code.default_code, max_length=256)),
                ('expires', models.DateTimeField(default=None, null=True)),
                ('generated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_on', models.DateTimeField(default=None, null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_codes_generated', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
