# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 03:08
from __future__ import unicode_literals

import ISS.models.registration_code
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0040_accesscontrolgroup_accesscontrollist'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='allow_video_embed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='black_groups',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_acls', to='ISS.AccessControlGroup'),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='black_posters',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_acls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='white_groups',
            field=models.ManyToManyField(blank=True, related_name='whitelisted_acls', to='ISS.AccessControlGroup'),
        ),
        migrations.AlterField(
            model_name='accesscontrollist',
            name='white_posters',
            field=models.ManyToManyField(blank=True, related_name='whitelisted_acls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authpackage',
            name='logic_package',
            field=models.CharField(choices=[(b'ACL_CONTROLLED', b'ACL_CONTROLLED'), (b'ADMIN_REQUIRED', b'ADMIN_REQUIRED'), (b'PERMISSIVE', b'PERMISSIVE')], default=b'PERMISSIVE', max_length=256),
        ),
        migrations.AlterField(
            model_name='poster',
            name='recovery_code',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='expires',
            field=models.DateTimeField(default=ISS.models.registration_code.default_expires, null=True),
        ),
    ]
