# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 01:58


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0041_auto_20171220_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
                ('obsolescing_ip', models.GenericIPAddressField(null=True)),
                ('obsolesced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='has_been_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postsnapshot',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISS.Post'),
        ),
    ]
