# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 02:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0045_auto_20180705_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='theme',
            field=models.CharField(choices=[(b'&T', b'&T'), (b'bibliotek', b'Bibliotek')], default=b'&T', max_length=256),
        ),
    ]
