# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 09:19
from __future__ import unicode_literals

from django.db import migrations

from email_normalize import normalize

def normalize_email(apps, schema_editor):
    Poster = apps.get_model('ISS', 'Poster')
    for poster in Poster.objects.all():
        poster.normalized_email = normalize(poster.email)
        poster.save()

class Migration(migrations.Migration):
    dependencies = [
        ('ISS', '0050_poster_normalized_email'),
    ]

    operations = [
        migrations.RunPython(normalize_email),
    ]
