# Generated by Django 2.2.8 on 2020-01-21 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0056_auto_20200121_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('vote_type', models.IntegerField(choices=[(0, 'Single Choice Voting'), (1, 'Multiple Choice Voting')], default=0)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ISS.Thread')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1024)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISS.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISS.Poll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll_option', 'voter')},
            },
        ),
    ]
