# Generated by Django 2.2.8 on 2020-01-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0056_auto_20200121_0440'),
        ('ISS', '0057_poll_polloption_pollvote'),
    ]

    operations = [
    ]
