# Generated by Django 2.2.9 on 2020-01-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISS', '0058_auto_20200126_0327'),
        ('ISS', '0058_merge_20200123_2359'),
    ]

    operations = [
    ]
